### ISSUE TITLE
Render leisure tags

### ISSUE THREAD

**Issue by sethfitz** [AmericanRedCross/posm-carto#10]
These are very useful for orientation. The missing tag that led us here was `leisure=park`, in http://www.openstreetmap.org/way/403946533

**Comment by almccon** [comment]
<img width="460" alt="screen shot 2016-05-04 at 4 may 6 46 12" src="https://cloud.githubusercontent.com/assets/1212178/15016014/f1d6467a-11c3-11e6-88c3-d461472a2e8f.png">
