### ISSUE TITLE
Label buildings

### ISSUE THREAD

**Issue by sethfitz** [AmericanRedCross/posm-carto#11]
If a building has a name, use that. If a building has a house number, use that.

These are both useful for orientation and also represent data that is collected using OMK.

**Comment by aawiseman** [comment]
Agreed, people often refer to the building names as landmarks

**Comment by almccon** [comment]
Can you point me to a neighborhood in Ecuador or Liberia (just the two extracts I happen to have at the moment) that has good house numbers? I already have house numbers rendering (tested against Seattle) but I don't see any in Huaquillas.

Also, for names, you mean the `name` tag, not the rarely-used `addr:housename` tag?

**Comment by almccon** [comment]
Buildings have names now, which I think happened in 1e72049d357847704ea055ba02c72b28a64a6f6e
![screen shot 2016-05-18 at 18 may 6 32 59](https://cloud.githubusercontent.com/assets/1212178/15379996/017db356-1d27-11e6-8e33-e09d005799bb.png)

I can't really find any `addr:housenumber` in my Ecuador extract, but they do show up for my Washington State extract starting at z18, so I'm calling this good.

![screen shot 2016-05-18 at 18 may 6 38 05](https://cloud.githubusercontent.com/assets/1212178/15380068/ac40d7c8-1d27-11e6-9789-3e0316d8f5fa.png)
