### ISSUE TITLE
Refine lowzoom style with Natural Earth for use as locator map

### ISSUE THREAD

**Issue by almccon** [AmericanRedCross/posm-carto#20]
See https://github.com/AmericanRedCross/posm/issues/62#issuecomment-214873758

Convenient for figuring out just where one is in the world in order to zoom into an area where local data is available.

**Comment by almccon** [comment]
Some progress. Some labels wouldn't hurt, either.

<img width="587" alt="screen shot 2016-04-29 at 29 apr 6 02 22" src="https://cloud.githubusercontent.com/assets/1212178/14932943/c1bcd784-0e34-11e6-8570-8abcb3bea52b.png">

**Comment by almccon** [comment]
Now pulling labels from Natural Earth too.

![screen shot 2016-05-04 at 4 may 5 34 13](https://cloud.githubusercontent.com/assets/1212178/15033347/8fc0a6c8-121e-11e6-804c-4b0da4e3585e.png)

**Comment by sethfitz** [comment]
Yay! Now we can more easily find where the detailed data is available.
