### ISSUE TITLE
Overly tight line heights on amenity labels

### ISSUE THREAD

**Issue by sethfitz** [AmericanRedCross/posm-carto#22]
<img width="168" alt="screen shot 2016-05-26 at 4 01 34 pm" src="https://cloud.githubusercontent.com/assets/45/15593037/7e8f9012-235d-11e6-8bfa-6303b6c25c02.png">

Could be retina-related, in which case it's a Mapnik bug. These are rendered using 3.5.13.

**Comment by almccon** [comment]
Looks good on retina:
<img width="347" alt="screen shot 2016-05-26 at 26 may 4 39 11" src="https://cloud.githubusercontent.com/assets/1212178/15593384/81911012-2360-11e6-93d7-91540ae218b9.png">

bad on non-retina:
![screen shot 2016-05-26 at 26 may 4 39 23](https://cloud.githubusercontent.com/assets/1212178/15593389/8aaceffe-2360-11e6-830e-93b01c9054fd.png)
On 3.5.13

**Comment by sethfitz** [comment]
Durr. Yes. I was browsing w/ OSM, which doesn't know about the retina tiles.

**Comment by almccon** [comment]
I just removed text-line-spacing for those, and it looks fine in both now. 

Retina:
<img width="232" alt="screen shot 2016-05-26 at 26 may 4 47 07" src="https://cloud.githubusercontent.com/assets/1212178/15593487/8548f7a0-2361-11e6-9919-a8d9ce38e569.png">

Non retina:
![screen shot 2016-05-26 at 26 may 4 46 38](https://cloud.githubusercontent.com/assets/1212178/15593481/73d3df6c-2361-11e6-8c94-f8c411802c74.png)
