### ISSUE TITLE
admin boundaries

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/posm-carto#5]
admin boundaries didn't seem to be included in the style

**Comment by almccon** [comment]
Oops, those are easy to forget when you're mainly testing on extracts. Which admin levels would you find most useful? Or should we show all of them?

And do the different admin levels needs to be easily distinguishable, or can they all use basically the same styling?

**Comment by almccon** [comment]
I just added some quick (and unlabeled) admin boundaries, down to admin_level=8. Right now they're just a gray dashed line. Let me know how these work in the field and I'm happy to tweak them.

<img width="674" alt="screen shot 2016-03-13 at 10 40 58 pm" src="https://cloud.githubusercontent.com/assets/1212178/13735939/bfad7a3a-e96c-11e5-913c-305509f80f66.png">

**Comment by almccon** [comment]
Sounds like there were no complaints about these from the field.

**Comment by dalekunce** [comment]
can you add the higher level admins (admin0-admin6) these are missing and make regional way finding difficult.

**Comment by almccon** [comment]
They should already be enabled. admin0 gets a solid black line, and all the others have the same dashed gray. I'll admit it's not pretty (and I'll give them another styling pass) but they should be in there as of March 13.

I'm using geofabrik extracts for testing the style. Maybe the POSM extract pipeline is dropping borders somewhere?

**Comment by almccon** [comment]
Here's what I see with an Ecuador extract, zoomed way out:

![screen shot 2016-04-19 at 19 apr 11 30 07](https://cloud.githubusercontent.com/assets/1212178/14650972/be34f64c-0622-11e6-8da5-944cd615e868.png)

**Comment by dalekunce** [comment]
yeah maybe the posm extract dropped the data somehow. That looks good enough for me. :)
